export const APP_ROUTER = {
    INDEX: "/",
    //
    HOME: "/home",
    COMPONENT: "/component",
    USER: "/user",
    PRODUCT: "/product",
    PRODUCTDETAIL: `/product/:id`,
    ADD_PRODUCT: "/product/add-product",
    LISTUSER: "/user",
    STORE: "/store",
    ADD_STORE: "/store/add-store",
    CATEGORY: "/category",
    NEEDS_COLLECTIONS: "/needs-collection",
    ORDERDELIVERED: "/order_delivered",
    ORDERDELIVERING: "/order_delivering",
    ORDERTRANS: "/order_trans",
    ORDERWAIT: "/order_wait",
    AUTH: "/auth",
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    CHANGE_PASSWORD: "change-password",
    REFRESH_TOKEN: "/auth/accessToken-generate",
    LOGOUT: "/auth/logout",
};
